### ISSUE TITLE
坐等大佬

### ISSUE THREAD

**Issue by guoruibiao** [huangz1990/RedisGuide-code#1]
先👍为敬。

**Comment by huangzworks** [comment]
代码已上线，感谢支持！😁

**Comment by SCUT007** [comment]
作者，您好，string/test_article.py中，setUp函数如果使用self.id = "10086"，会报如下错误，需要将这里的id重新命名为其他变量名
Traceback (most recent call last):
  File "D:\Program Files\Python\Python38\lib\unittest\case.py", line 684, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "D:\Program Files\Python\Python38\lib\unittest\case.py", line 602, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "D:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pycharm\teamcity\unittestpy.py", line 143, in addError
    self.report_fail(test, 'Error', err)
  File "D:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pycharm\teamcity\unittestpy.py", line 194, in report_fail
    test_id = self.get_test_id_with_description(test)
  File "D:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pycharm\teamcity\unittestpy.py", line 40, in get_test_id_with_description
    test_id = test.id()
TypeError: 'str' object is not callable
